version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  labels:
  - "pr: dependencies"
  versioning-strategy: increase
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: got
    versions:
    - 11.8.1
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: postcss-scss
    versions:
    - 3.0.4
  - dependency-name: v8-compile-cache
    versions:
    - 2.2.0
  - dependency-name: lodash
    versions:
    - 4.17.20
